<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="shah4corp" failures="3" tests="4" name="Banking App Test(failed)" time="53.5" errors="0" timestamp="2024-08-11T09:53:06 IST">
  <testcase classname="com.inetBanking.testCases.TC_LoginDDT_002" name="LoginDDT" time="7.085">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBanking.testCases.TC_LoginDDT_002.LoginDDT(TC_LoginDDT_002.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginDDT -->
  <testcase classname="com.inetBanking.testCases.TC_LoginDDT_002" name="LoginDDT" time="3.309">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBanking.testCases.TC_LoginDDT_002.LoginDDT(TC_LoginDDT_002.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginDDT -->
  <testcase classname="com.inetBanking.testCases.TC_LoginDDT_002" name="LoginDDT" time="4.741">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBanking.testCases.TC_LoginDDT_002.LoginDDT(TC_LoginDDT_002.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginDDT -->
  <testcase classname="com.inetBanking.testCases.TC_AddCustomerTest_003" name="addNewCustomer" time="31.43"/>
</testsuite> <!-- Banking App Test(failed) -->
